In [4]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import dash
import dash_table
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output


df=pd.read_excel(r'C:\Users\IN22912959\OneDrive - Tesco\Documents\Resets\Final_Pivot_Data_SBR_Vinegar_Phase1_v1.xlsx')
# else:
#     df=pd.read_excel(r'C:\Users\IN22912959\OneDrive - Tesco\Documents\Resets\Final_Pivot_Data_Salmon_Phase2_v1.xlsx')
    




suppliers_list=list(df['supplier_name'].unique())
suppliers_list

product_block_list=list(df['product_block'].unique())
product_block_list

PB_cols = suppliers_list.copy()
PB_cols.insert(0,'Product Block')
PB_cols.insert(len(PB_cols),'Minimum')

supplier_feedback_cols1=['supplier_name','product_block','TPNB','Total_Product_Bid%']
supplier_feedback_cols1_replacement=['Supplier Name','Product Block','TPNB','Total Product Bid %']
    

supplier_feedback_cols2=['product_block', 'TPNB', 'description', 'volume','Supplier_Quantile_Rank', 'Position']
supplier_feedback_cols2_replacment=['Product Block', 'TPNB', 'Description', 'Volume','Supplier Quantile Rank', 'Position']


supplier_feedback_cols3=['product_block','Bid_%','competitive','reason']
supplier_feedback_cols3_replacement=['Product Block','Bid %','Competitive','Reason']

block_grid_cols=['product_block',
 'TPNB',
 'volume',
 'negotiation_index',
 'current_cost',
 'No_Bids',
 'best_supplier',
 'vol_avg',
 'NI_Avg',
 'Action_Priority',
 'lowest_bidder_cost',
 'Risk',
 'max_bid_supplier']
block_grid_cols.extend(suppliers_list)


block_grid_cols_replacement=['Product Block',
 'TPNB',
 'Volume',
 'Negotiation Index',
 'Current Cost',
 'No Bids',
 'Best Supplier',
 'Vol Avg',
 'NI Avg',
 'Action Priority',
 'Lowest Bidder Cost',
 'Risk',
 'Max Bid Supplier']
block_grid_cols_replacement.extend(suppliers_list)


app=dash.Dash()



cols=['product_block', 'TPNB', 'description', 'cost_component',
       'current_cost', 'quoted_cost', 'best_bid', 'best_supplier', 'volume',
       'Impact']
cols_replacement=['Product Block','TPNB','Description','Cost Component','Current Cost','Quoted Cost','Best Bid','Best Supplier','Volume','Impact']


external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

tabs_styles = {
    'height': '44px'
}
tab_style = {
    'borderBottom': '1px solid #d6d6d6',
    'padding': '6px',
#     'fontWeight': 'bold',
    'color':'#000'
}

tab_selected_style = {
    'borderTop': '1px solid #d6d6d6',
    'borderBottom': '1px solid #d6d6d6',
    'backgroundColor': '#00539f',
    'color': 'white',
    'padding': '6px'
}
headings={'color':'#00539f','background-color':'#fff','text-align':'center'}


app.layout=html.Div([
    html.Div([],style={'background-color':'#00539f','height':'5px','width':'100%'}),
    
    html.Div([
        html.Img(src="https://www.logosurfer.com/wp-content/uploads/2018/03/tesco-logo_0.png",style={'float':'left','height':'20px','padding':'2px'}),
        html.Label("Bid Summary Tool - Supplier Analysis",style=headings),
        
    ],style={'height':'30px','background-color':'#fff'}),
    
    html.Div([
    dcc.Tabs(id='tabs', value='tab-1', children=[
        dcc.Tab(label='Supplier', value='tab-1',style=tab_style, selected_style=tab_selected_style,children=[
            dcc.Dropdown(id="supplier-dropdown",
                    options=[
                        {'label': i, 'value': i} for i in suppliers_list
                    ],
                    value=suppliers_list[0]
                     
            ),
            
            html.Div([
                html.Div([
                dcc.Graph(id='plot')
                ],style={'display':'inline-block','width':'50%'}),
            
                html.Div([
                    dcc.Graph(id='plot_2')
                    ],style={'display':'inline-block','width':'50%'}),
                ],style={'width': '100%', 'height': '450px'}
            ),
            html.Label("Top Oppurtunities",style={'background-color':'#ccc','color':'#000','text-align':'center'}),
            dash_table.DataTable(
                    id='computed-table',
                    columns=[
                            {"name": i, "id": i} for i in cols_replacement
                        ],
                    style_as_list_view=False,
                    style_cell={'padding': '5px'},
                    style_header={
                        'backgroundColor': '#00539f',
                        'fontWeight': 'bold',
                        'color':'#fff'
                    },
                    style_data={
                        'color':'#00539f'
                    }
        
            ),
            html.Div([
                    html.Div([
                        dcc.Dropdown(
                            id="product_block_dropdown",
                            multi=True,
                            placeholder = "Select a Product Block",
                            # options = [
                            #     {"label": i , "value": i} for i in block_list
                            # ],
                            # value = block_list[0],
                            style={'background-color': '#C0C0C0', 'color': '#000'}
                        ),
                    ], style={'display': 'inline-block', 'width': '30%'}),
                    html.Div([
                        dcc.Dropdown(
                            id="TPNB_dropdown",
                            multi=True,
                            placeholder = "Select a TPNB",
                            style={'background-color': '#C0C0C0', 'color': '#000'}
                        ),
                    ], style={'display': 'inline-block', 'width': '70%'}),
                ]),
                html.Div([
                        html.Div([
                            dcc.Graph(
                                id="Quoted_Price_Comparison",
                                style={'height': '400px'}
                            )
                        ], style={'display': 'inline-block', 'width': '50%'}),

                        html.Div([
                            dcc.Graph(
                                id="Total_Price_Comparison",
                                style={'height': '400px'}
                            )
                        ], style={'display': 'inline-block', 'width': '50%'}),

                    ], style={'width': '100%', 'height': '400px'}
                ),
            
                ]
        ),
        dcc.Tab(label='Block', value='tab-2',style=tab_style, selected_style=tab_selected_style,children=[
            dcc.Dropdown(id="product_block-dropdown",
                         multi=True,
                    options=[
                        {'label': i, 'value': i} for i in product_block_list
                    ],
                    value=product_block_list,
                    style={'background-color':'#000','color':'#000'}
                     
            ),
            html.Div([
                dcc.Graph(id='Supplier Coverage plot')
                ],style={'display':'inline-block','width':'100%'}
            ),
            html.Label("Block Grid",style={'background-color':'#ccc','color':'#000','text-align':'center'}),
            dash_table.DataTable(
                    id='block_table',
                    columns=[
                            {"name": i, "id": i} for i in list(block_grid_cols_replacement)
                        ],
                    style_as_list_view=False,
                    style_cell={'padding': '5px'},
                    style_header={
                        'backgroundColor': '#00539f',
                        'fontWeight': 'bold',
                        'color':'#fff'
                    },
                    style_data={
                        'color':'#00539f'
                    },
                style_table={'overflowX': 'scroll'},
                style_data_conditional=[
                    {
                               'if': {
                                        'column_id': 'Risk',
                                        'filter_query': '{Risk} eq "Yes"'
                                    },
                                      'backgroundColor': '#EE1C2E',
                                      'color': 'white'            
                    },
                    {
                        'if': {
                            'column_id': 'Risk',
                            'filter_query': '{Risk} eq "No"'
                                },
                                'backgroundColor': '#00B050',
                                'color': 'white',
                    },
                    {
                               'if': {
                                        'column_id': 'Action_Priority',
                                        'filter_query': '{Action_Priority} eq "HIGH"'
                                    },
                                      'backgroundColor': '#00B050',
                                      'color': 'white'            
                    },
                    {
                        'if': {
                            'column_id': 'Action_Priority',
                            'filter_query': '{Action_Priority} eq "LOW"'
                                },
                                'backgroundColor': '#EE1C2E',
                                'color': 'white',
                    },
                    {
                        'if': {
                            'column_id': 'Action_Priority',
                            'filter_query': '{Action_Priority} eq "MEDIUM"'
                                },
                                'backgroundColor': '#FFA826',
                                'color': 'white',
                    }
                    
                ]
        
            ),
            html.Div([
        dcc.Dropdown(
            id="pb_dropdown",
            multi=True,
            options=[
                {"label": i, "value": i} for i in product_block_list
            ],
            value=product_block_list,
            style={'background-color': '#C0C0C0', 'color': '#000'}
        ),
    ], style={'display': 'inline-block', 'width': '70%'}),

    html.Div([
        html.H4(children="Delivered Cost (Weighted average)"),
        dash_table.DataTable(
            id="Del_Cost_PB",
            columns=[{"name": i, "id": i} for i in PB_cols],
            style_as_list_view=False,
            style_cell={'padding': '5px'},
            style_header={
                'backgroundColor': '#00539f',
                'fontWeight': 'bold',
                'color':'#fff'
            },
            style_data={
                'color':'#00539f'
            },
        ),
    ]),

    html.Div([
        html.H4(children="Total Cost"),
        dash_table.DataTable(
            id="Total_Cost_PB",
            columns=[{"name": i, "id": i} for i in PB_cols],
            style_as_list_view=False,
            style_cell={'padding': '5px'},
            style_header={
                'backgroundColor': '#00539f',
                'fontWeight': 'bold',
                'color':'#fff'
            },
            style_data={
                'color':'#00539f'
            },
        ),
    ]),

    html.Div([
        html.H4(children="Savings"),
        dash_table.DataTable(
            id="Savings_PB",
            columns=[{"name": i, "id": i} for i in PB_cols],
            style_as_list_view=False,
            style_cell={'padding': '5px'},
            style_header={
                'backgroundColor': '#00539f',
                'fontWeight': 'bold',
                'color':'#fff'
            },
            style_data={
                'color':'#00539f'
            },
        ),
    ])
            
            
        ]),
dcc.Tab(label='Supplier Feedback', value='tab-3',style=tab_style, selected_style=tab_selected_style,children=[
            html.Div([
                html.Div(style={'float':'left','width':'20%'},children=[
                    dcc.RadioItems(id="supplier-checklist",
                            options=[
                                {'label': i, 'value': i} for i in suppliers_list
                            ],
                            value=suppliers_list[0],
                            style={'background-color':'#fff','color':'#000'}
                     
                        )
                    
                ])
                
            ]),
            html.Div([
                    dash_table.DataTable(
                        id="Supplier_Feedback",
                        columns=[{"name": i, "id": i} for i in supplier_feedback_cols1_replacement],
                        style_as_list_view=False,
                        style_cell={'padding': '5px'},
                        style_header={
                            'backgroundColor': '#00539f',
                            'fontWeight': 'bold',
                            'color':'#fff'
                        },
                        style_data={
                            'color':'#00539f'
                        }
                    )
                    
                ],style={'float':'right','width':'80%'}
            ),
        html.Div(id="Overall_Position",
                 
                 
        ),
        html.Div(
            html.Label(children="Position Reason",style={"float":"left"}),
                        id="Reason",
        ),
        html.Div([
            dash_table.DataTable(
            id="Product_Block_Position",
                columns=[{"name": i, "id": i} for i in supplier_feedback_cols3_replacement],
                style_as_list_view=False,
                    style_cell={'padding': '5px'},
                style_header={
                        'backgroundColor': '#00539f',
                        'fontWeight': 'bold',
                        'color':'#fff'
                    },
                    style_data={
                        'color':'#00539f'
                    },
                style_data_conditional=[
                    {
                               'if': {
                                        'column_id': 'Competitive',
                                        'filter_query': '{Competitive} eq "Non Competitive"'
                                    },
                                      'backgroundColor': '#EE1C2E',
                                      'color': 'white'            
                    },
                    {
                        'if': {
                            'column_id': 'Competitive',
                            'filter_query': '{Competitive} eq "Competitive"'
                                },
                                'backgroundColor': '#00B050',
                                'color': 'white',
                    },
                {
                        'if': {
                            'column_id': 'Competitive',
                            'filter_query': '{Competitive} eq "Competitive_2"'
                                },
                                'backgroundColor': '#00B050',
                                'color': 'white',
                    }]
                
                
                
            )
        ]),
           html.Div([
                html.H4(children="Product Level Position"),
                dash_table.DataTable(
                    id="supplier_feedback_grid",
                    columns=[{"name": i, "id": i} for i in supplier_feedback_cols2_replacment],
                    style_as_list_view=False,
                    style_cell={'padding': '5px'},
                    style_header={
                        'backgroundColor': '#00539f',
                        'fontWeight': 'bold',
                        'color':'#fff'
                    },
                    style_data={
                        'color':'#00539f'
                    },
                    style_data_conditional=[
                    {
                               'if': {
                                        'column_id': 'Position',
                                        'filter_query': '{Position} eq "NON COMPETITIVE"'
                                    },
                                      'backgroundColor': '#EE1C2E',
                                      'color': 'white'            
                    },
                    {
                        'if': {
                            'column_id': 'Position',
                            'filter_query': '{Position} eq "COMPETITIVE"'
                                },
                                'backgroundColor': '#00B050',
                                'color': 'white',
                    },
                    {
                               'if': {
                                        'column_id': 'Position',
                                        'filter_query': '{Position} eq "NOT BID"'
                                    },
                                      'backgroundColor': '#FFA826',
                                      'color': 'white'            
                    }
                    
                ]
                ),
    ]),
    
    ]),
    ]),
    html.Div(id='tabs-content')
    ]),
    
],style={'font-family': 'Tesco'})




@app.callback(
    [Output("Supplier_Feedback","data"),
     Output("Overall_Position","children"),
    Output("Reason","children"),
    Output("Product_Block_Position","data")],
    [Input("supplier-checklist","value")])
def supplier_feedback_details(isupplier):
    
    cols=['supplier_name','product_block','TPNB','volume','negotiation_index','current_cost','No_Bids','best_supplier','Supplier_Quantile_Rank']
    df3=df[cols][(df['supplier_name']==isupplier)&(df['cost_component']=='Delivered Cost')&(df['Is_TPNB']==1)].drop_duplicates()
    product_block_count=df3.product_block.nunique()

    df4=df3.groupby(['supplier_name'])['product_block','TPNB'].nunique().reset_index()

    df['TPNB'].nunique()

    df4['Total_Product_Bid%']=round((df4['TPNB']/df['TPNB'].nunique())*100,0)

    upper_quartile=df3[(df3['Supplier_Quantile_Rank'].isin([1,2]))&(df3['supplier_name']==isupplier)]
    upper_quartile=upper_quartile.groupby(['product_block'])['Supplier_Quantile_Rank'].count().reset_index()
    upper_quartile

    lower_Quartile=df3[(df3['Supplier_Quantile_Rank'].isin([3,4]))&(df3['supplier_name']==isupplier)]
    lower_Quartile=lower_Quartile.groupby(['product_block'])['Supplier_Quantile_Rank'].count().reset_index()
    lower_Quartile


    upper_quartile_tpnb=sum(upper_quartile['Supplier_Quantile_Rank'])

    lower_quartile_tpnb=sum(lower_Quartile['Supplier_Quantile_Rank'])

    top_2_quartile_per=(upper_quartile_tpnb/(upper_quartile_tpnb+lower_quartile_tpnb))*100

    df4['Overall_position']=np.where(((df4['Total_Product_Bid%']>60)&(top_2_quartile_per>25)),'Competitive',
                                     np.where(((df4['Total_Product_Bid%']>40)&(top_2_quartile_per>40)),'Competitive_2','Non Competitive'))
    
    df4['Reason']=np.where(((df4['Total_Product_Bid%']>60) & (top_2_quartile_per>25)),'You bid on more than 60% of the block and more than 25% of your bids were competitive',
                                 np.where(((df4['Total_Product_Bid%']>40) & (top_2_quartile_per>40)),'You have not bid on a high % of products but more than 40% of your bids are competitive',
                                        np.where((df4['Total_Product_Bid%']<40),'You have bid on a very low number of products','A high percentage of your bids are not in the competitive zone')))
    df4
    cols=['supplier_name', 'product_block', 'TPNB', 'Total_Product_Bid%']
    df5=df4[cols]
    reason=df4['Reason'].reset_index()
    
    
    quartile=upper_quartile.merge(lower_Quartile,on=['product_block'],how='outer')

    quartile['upper_bid%']=((quartile['Supplier_Quantile_Rank_x'])/(quartile['Supplier_Quantile_Rank_x']+quartile['Supplier_Quantile_Rank_y']))*100

    tpnb_bid=df3.groupby(['product_block'])['TPNB'].nunique().reset_index()
    tpnb_bid

    total_tpnb=df.groupby(['product_block'])['TPNB'].nunique().reset_index()
    total_tpnb

    bid_per=tpnb_bid.merge(total_tpnb,how='inner',on=['product_block'])

    bid_per['Bid_%']=(bid_per['TPNB_x']/bid_per['TPNB_y'])*100
    bid_per

    product_block_position=quartile.merge(bid_per[['product_block','Bid_%']],on=['product_block'],how='outer')
    product_block_position

    product_block_position['competitive']=np.where(((product_block_position['Bid_%']>=80) & (product_block_position['upper_bid%']>=25)),'Competitive',
                                             np.where(((product_block_position['Bid_%']>=60) & (product_block_position['upper_bid%']>=40)),'Competitive_2','Non Competitive'))



    product_block_position['reason']=np.where(product_block_position['competitive']=='Competitive','You bid on more than 80% of the block and more than 25% of your bids were competitive',
                                     np.where(product_block_position['competitive']=='Competitive_2','You bid on less than 60% of the block and less than 40% of them were competitive','You bid on more than 80% of the block but less than 25% of your bids were competitive'))
    
    cols=['product_block','Bid_%','competitive','reason']
    product_block_position=product_block_position[cols]
    pbs=df['product_block'].drop_duplicates().to_frame()
    product_block_position=pbs.merge(product_block_position,on=['product_block'],how='left')
    product_block_position['Bid_%']=product_block_position['Bid_%'].fillna(0)
    product_block_position['competitive']=product_block_position['competitive'].fillna('Non Competitive')
    product_block_position['reason']=product_block_position['reason'].fillna('You bid on less than 60% of the block and less than 40% of them were competitive')
    product_block_position
    product_block_position.columns=['Product Block','Bid %','Competitive','Reason']
    new_cols=['Supplier Name','Product Block','TPNB','Total Product Bid %']
    df5.columns=new_cols
    return df5.to_dict('records'),[html.Div([html.P(children="Overall Position : "+df4['Overall_position'][0],style={'color': '#00539f', 'fontSize':'20px','background-color':'#ccc','padding-top':'82px'})])],[html.P(children="Position Reason:"+ df4['Reason'][0] ,style={'color': '#00539f', 'fontSize': '20px','background-color':'#ccc','padding-top':'20px'})],product_block_position.round(2).to_dict('records')




@app.callback(
    Output('plot', 'figure'),
    [Input('supplier-dropdown', 'value')])
def callback_color(prod):
    df_sup=df[(df['supplier_name']==prod)&(df['cost_component']=='Delivered Cost')]
    pivot = df_sup[['product_block','Is_TPNB','TPNB']].pivot_table(index=['product_block'],columns=['Is_TPNB'],aggfunc='count')
    pivot=pivot.fillna(0)
    pivot.columns = pivot.columns.droplevel(0)
    pivot_2 = pivot.reset_index().rename_axis(None, axis=1)
    fig = px.bar(pivot_2, x='product_block', y=1,title="TPN Coverage %",labels={
                     "1": "No of TPN's",
                     "product_block": "Product Block"
                 })

    
    return fig



@app.callback(
    Output('plot_2', 'figure'),
    [Input('supplier-dropdown', 'value')])
def savings(prod):
    df_sup=df[(df['supplier_name']==prod)&(df['cost_component']=='Delivered Cost')&(df['Is_NPD']==0)&(df['Is_TPNB']==1)]
    pivot = df_sup[['product_block','Savings']].pivot_table(index=['product_block'],aggfunc='sum')
    pivot=pivot.fillna(0)
    pivot_2 = pivot.reset_index().rename_axis(None, axis=1)
    pivot_2.head(2)
    pivot_2["Color"] = np.where(pivot_2["Savings"]>=0, 'green', 'red')

    fig = go.Figure()
    fig.add_trace(
        go.Bar(x=pivot_2['Savings'],
            y=pivot_2['product_block'],
            marker_color=pivot_2['Color'],
            orientation='h'
            ))
    fig.update_layout(title_text='Increment over current COGS',barmode='stack')

    return fig
    


@app.callback(
    Output('computed-table', 'data'),
    [Input('supplier-dropdown', 'value')])
def top_oppurtunities(prod):
    cols=['supplier_name','product_block','TPNB','description','Is_NPD','Is_TPNB','cost_component','current_cost','quoted_cost','best_bid','best_supplier','volume','Impact']
    df_sup=df[cols].drop_duplicates()
    df_sup_2=df_sup[(df['supplier_name']==prod)&(df_sup['Is_NPD']==0)&(df_sup['Is_TPNB']==1)]
    pivot = df_sup_2.groupby(['TPNB','cost_component'],as_index=False).agg({
        'current_cost':'sum',
        'quoted_cost':'sum',
        'best_bid':'sum',
        'Impact':'sum'

    }).reset_index(drop = True)
    df_2=pivot.sort_values(by=['Impact'],ascending=False).head(14)
    df3=df_2[['TPNB']].merge(df_sup[df_sup['supplier_name']==prod],how='inner',left_on=['TPNB'],right_on=['TPNB'])
    cols=['product_block','TPNB','description','cost_component','current_cost','quoted_cost','best_bid','best_supplier','volume','Impact']
    df4=df3[cols].drop_duplicates()
    df5=df4.sort_values(by=['Impact'],ascending=False).head(14)
    df5['Impact']=df5['Impact'].round(1)
    new_cols=['Product Block','TPNB','Description','Cost Component','Current Cost','Quoted Cost','Best Bid','Best Supplier','Volume','Impact']
    df5.columns=new_cols
    return df5.round(2).to_dict('records')
    




@app.callback(Output('tabs-content', 'children'),
              [Input('tabs', 'value')])
def render_content(tab):
    if tab == 'tab-1':
        return html.Div([
            html.H3('Supplier Leve Bid Analysis')
        ])
    elif tab == 'tab-2':
        return html.Div([
            html.H3('Block Level Bid Analysis')
        ])
    elif tab == 'tab-3':
        return html.Div([
            html.H3('Supplier Feedback')
        ])



@app.callback(
    Output('Supplier Coverage plot', 'figure'),
    [Input('product_block-dropdown', 'value')])
def supplier_coverage_plot(prod):
    df_sup=df[(df['product_block'].isin(prod))&(df['cost_component']=='Delivered Cost')]
    pivot_Block_Covg = df_sup[['supplier_name','product_block','Is_TPNB','TPNB']].pivot_table(index=['supplier_name','product_block'],columns=['Is_TPNB'],aggfunc='count')
    pivot_Block_Covg = pivot_Block_Covg.fillna(0)
    pivot_Block_Covg.columns = pivot_Block_Covg.columns.droplevel(0)
    pivot_Block_Covg = pivot_Block_Covg.reset_index().rename_axis(None, axis=1)
    if(0 in pivot_Block_Covg.columns):
        pivot_Block_Covg['0_perc'] = pivot_Block_Covg[0] * 100 / (pivot_Block_Covg[0] + pivot_Block_Covg[1])
        pivot_Block_Covg['1_perc'] = pivot_Block_Covg[1] * 100 / (pivot_Block_Covg[0] + pivot_Block_Covg[1])
    else:
        pivot_Block_Covg['1_perc'] = pivot_Block_Covg[1] * 100 / (pivot_Block_Covg[1])


    fig = px.bar(pivot_Block_Covg, x='supplier_name', y='1_perc',title="Supplier Coverage %",
                 color="product_block",
                 barmode="group",
                 labels={
                         "1_perc": "% Bid",
                         "supplier_name": "Supplier Name",
                         "product_block":"Product Block"
                     })

    return fig
#     df_sup=df[(df['product_block']==prod)&(df['cost_component']=='Delivered Cost')]
#     pivot = df_sup[['supplier_name','product_block','Is_TPNB','TPNB']].pivot_table(index=['supplier_name','product_block'],columns=['Is_TPNB'],aggfunc='count')
#     pivot.columns = pivot.columns.droplevel(0)
#     pivot_2 = pivot.reset_index().rename_axis(None, axis=1)

#     cols = [0, 1]
#     pivot_2[cols] = pivot_2[cols].div(pivot_2[cols].sum(axis=1), axis=0).multiply(100)
#     pivot_2.fillna(0)
#     fig = px.bar(pivot_2, x='supplier_name', y=1,title="Supplier Coverage %",
#                  color="product_block",
#                  barmode="group",
#                  labels={
#                          "1": "%",
#                          "supplier_name": "Supplier Name",
#                          "product_block":"Product Block"
#                      })
    

    
#     return fig

@app.callback(
    Output('block_table', 'data'),
    [Input('product_block-dropdown', 'value')])
def block_grid(prod):
    cols=['product_block','TPNB','volume','negotiation_index','current_cost','No_Bids','best_supplier']
    df2=df[cols][(df['product_block'].isin(prod))&(df['cost_component']=='Delivered Cost')&(df['Is_TPNB']==1)].drop_duplicates()
    df2=df2.sort_values(by=['negotiation_index'],ascending=False)
    vol_avg=[]
    for i in range(0,len(df2)):
        avg=df2.iloc[i:]['volume'].mean()
        vol_avg.append(avg)

    df2['vol_avg']=vol_avg
    df2['NI_Avg']=df2['negotiation_index'].mean()
    df2['Action_Priority'] = np.where(((df2['volume']>df2['vol_avg']) & (df2['negotiation_index']>df2['NI_Avg'])),'HIGH',np.where(((df2['volume']<df2['vol_avg']) & (df2['negotiation_index']<df2['NI_Avg'])),'LOW','MEDIUM'))

    lowest_bid=df[(df['quoted_cost']!=0)&(df['cost_component']=='Delivered Cost')].groupby(['TPNB']).agg({'quoted_cost':'min'}).reset_index()
    lowest_bid=lowest_bid.rename(columns={'quoted_cost':'lowest_bidder_cost'})


    df2=df2.merge(lowest_bid,how='inner',on=['TPNB'])
    df2['Risk'] = np.where(((df2['lowest_bidder_cost']>df2['current_cost']) | (df2['No_Bids']<2)),'Yes','No')

    max_bid=df[(df['quoted_cost']!=0)&(df['cost_component']=='Delivered Cost')].groupby(['TPNB']).agg({'quoted_cost':'max'}).reset_index()
    max_bid=max_bid.merge(df[['TPNB','quoted_cost','supplier_name']],how='inner',on=['quoted_cost','TPNB'])
    max_bid=max_bid.rename(columns={'quoted_cost':'max_bidder_cost',
                                   'supplier_name':'max_bid_supplier'})
    df2=df2.merge(max_bid[['TPNB','max_bid_supplier']],how='inner',on=['TPNB'])

    block_grid=df[(df['cost_component']=='Delivered Cost')].groupby(['TPNB','supplier_name']).agg({'Is_TPNB':'mean'}).reset_index()
    block_grid=block_grid.sort_values(by=['Is_TPNB'],ascending=False)
    block_grid['Is_TPNB']=block_grid['Is_TPNB']*100
    block_grid = block_grid.pivot_table(index=['TPNB'],columns=['supplier_name'])
    block_grid.columns = block_grid.columns.droplevel(0)
    block_grid = block_grid.reset_index().rename_axis(None, axis=1)


    df2=df2.merge(block_grid,how='inner',on=['TPNB']).round(2) 
    new_cols=['Product Block',
              'TPNB',
              'Volume',
              'Negotiation Index',
              'Current Cost',
              'No Bids',
              'Best Supplier',
              'Vol Avg',
              'NI Avg',
              'Action Priority',
              'Lowest Bidder Cost',
              'Risk',
              'Max Bid Supplier']
    new_cols.extend(suppliers_list)
    df2.columns=new_cols
    
    return df2.round(2).to_dict('records')
    
    
@app.callback(
    Output("product_block_dropdown", "options"),
    [Input("supplier-dropdown", "value")]
)
def Product_block_List(iSupplier):
    block_supp_list = list(
        df[(df['supplier_name'] == iSupplier) & (df['Is_TPNB'] == 1)]['product_block'].unique())
    return [{'label': i, 'value': i} for i in block_supp_list]


@app.callback(
    Output("TPNB_dropdown", "options"),
    [Input("supplier-dropdown", "value"),
     Input("product_block_dropdown", "value")]
)
def TPNB_List(iSupplier, iBlock):
    TPNB_block_supp_list = list(df[(df['supplier_name'] == iSupplier) &
                                         (df['product_block'].isin(iBlock)) & (df['Is_TPNB'] == 1)][
                                    'TPNB'].unique())
    return [{'label': i, 'value': i} for i in TPNB_block_supp_list]


@app.callback(
    Output("Quoted_Price_Comparison", "figure"),
    [Input("supplier-dropdown", "value"),
     Input("product_block_dropdown", "value"),
     Input("TPNB_dropdown", "value")]
)
def Quoted_Price_Comparison(iSupplier, iBlock, iTPNB):
    pivot_Quoted_Price_Comparison = df[(df['supplier_name'] == iSupplier) & (df['product_block'].isin(iBlock)) & ~(df['cost_component'] == 'Delivered Cost') &(df['TPNB'].isin(iTPNB))].groupby('cost_component').mean()[['quoted_cost', 'best_bid']]
    pivot_Quoted_Price_Comparison.reset_index(inplace=True)
    cost_component = list(pivot_Quoted_Price_Comparison['cost_component'])
    quoted_cost = list(pivot_Quoted_Price_Comparison['quoted_cost'])
    best_bid = list(pivot_Quoted_Price_Comparison['best_bid'])

    fig = go.Figure()
    fig.add_trace(go.Bar(x=cost_component, y=quoted_cost, name='Quoted Cost', marker_color='rgb(55, 83, 109)'))
    fig.add_trace(go.Bar(x=cost_component, y=best_bid, name='Best Bid', marker_color='rgb(26, 118, 255)'))

    fig.update_layout(
        title='Price Breakdown Comparison',
        xaxis_tickfont_size=8,
        xaxis=dict(
            title='Cost Component',
            titlefont_size=12,
            tickfont_size=10,
        ),
        legend=dict(
            x=0.6,
            y=1.0,
            bgcolor='rgba(255, 255, 255, 0)',
            bordercolor='rgba(255, 255, 255, 0)'
        ),
        barmode='group',
        bargap=0.15,  # gap between bars of adjacent location coordinates.
        bargroupgap=0.1  # gap between bars of the same location coordinate.
    )
    return fig


@app.callback(
    Output("Total_Price_Comparison", "figure"),
    [Input("supplier-dropdown", "value"),
     Input("product_block_dropdown", "value"),
     Input("TPNB_dropdown", "value")]
)
def Total_Price_Comparison(iSupplier, iBlock, iTPNB):
    pivot_Total_Price_Comparison = df[(df['supplier_name'] == iSupplier) &(df['product_block'].isin(iBlock)) & ~(df['cost_component'] == 'Delivered Cost') &(df['TPNB'].isin(iTPNB))].groupby('cost_component').mean()[['total_cost', 'best_total_cost']]
    pivot_Total_Price_Comparison.reset_index(inplace=True)
    cost_component = list(pivot_Total_Price_Comparison['cost_component'])
    total_cost = list(pivot_Total_Price_Comparison['total_cost'])
    best_total_cost = list(pivot_Total_Price_Comparison['best_total_cost'])

    fig = go.Figure()
    fig.add_trace(go.Bar(x=cost_component, y=total_cost, name='Total Cost', marker_color='rgb(55, 83, 109)'))
    fig.add_trace(go.Bar(x=cost_component, y=best_total_cost, name='Best Total Cost', marker_color='rgb(26, 118, 255)'))

    fig.update_layout(
        title='Total Cost Breakdown Comparison',
        xaxis_tickfont_size=8,
        xaxis=dict(
            title='Cost Component',
            titlefont_size=12,
            tickfont_size=10,
        ),
        legend=dict(
            x=0.6,
            y=1.0,
            bgcolor='rgba(255, 255, 255, 0)',
            bordercolor='rgba(255, 255, 255, 0)'
        ),
        barmode='group',
        bargap=0.15,  # gap between bars of adjacent location coordinates.
        bargroupgap=0.1  # gap between bars of the same location coordinate.
    )
    return fig

@app.callback(
    Output("Del_Cost_PB", "data"),
    [Input("pb_dropdown", "value")]
)
def Del_Cost_PB(iPBlock):
    pivot_Del_Cost_PB = pd.pivot_table(df[(df['product_block'].isin(iPBlock)) & 
    (df['cost_component'] == 'Delivered Cost')], values='quoted_cost_wgt', index=['product_block'],
    columns=['supplier_name'], aggfunc=np.sum)
    pivot_Del_Cost_PB.replace(0, np.nan,inplace=True)
    pivot_Del_Cost_PB['Minimum'] = pivot_Del_Cost_PB[pivot_Del_Cost_PB.columns].min(axis=1)
    pivot_Del_Cost_PB.reset_index(inplace=True)
    pivot_Del_Cost_PB.rename(columns={'product_block':'Product Block'},inplace=True)

    return pivot_Del_Cost_PB.round(2).to_dict('records')

@app.callback(
    Output("Total_Cost_PB", "data"),
    [Input("pb_dropdown", "value")]
)
def Total_Cost_PB(iPBlock):
    pivot_Total_Cost_PB = pd.pivot_table(df[(df['product_block'].isin(iPBlock)) & 
    (df['cost_component'] == 'Delivered Cost')], values='total_cost', index=['product_block'],
    columns=['supplier_name'], aggfunc=np.sum)
    pivot_Total_Cost_PB.replace(0, np.nan,inplace=True)
    pivot_Total_Cost_PB['Minimum'] = pivot_Total_Cost_PB[pivot_Total_Cost_PB.columns].min(axis=1)
    pivot_Total_Cost_PB.reset_index(inplace=True)
    pivot_Total_Cost_PB.rename(columns={'product_block':'Product Block'},inplace=True)

    return pivot_Total_Cost_PB.round(2).to_dict('records')

@app.callback(
    Output("Savings_PB", "data"),
    [Input("pb_dropdown", "value")]
)
def Savings_PB(iPBlock):
    pivot_Savings_PB = pd.pivot_table(df[(df['product_block'].isin(iPBlock)) & 
    (df['cost_component'] == 'Delivered Cost') & (df['Is_TPNB'] == 1) &
    (df['Is_NPD'] == 0)], values='Savings', index=['product_block'],
    columns=['supplier_name'], aggfunc=np.sum)
    pivot_Savings_PB.replace(0, np.nan,inplace=True)
    pivot_Savings_PB['Minimum'] = pivot_Savings_PB[pivot_Savings_PB.columns].min(axis=1)
    pivot_Savings_PB.reset_index(inplace=True)
    pivot_Savings_PB.rename(columns={'product_block':'Product Block'},inplace=True)

    return pivot_Savings_PB.round(2).to_dict('records')

@app.callback(
    Output("supplier_feedback_grid", "data"),
    [Input("supplier-checklist", "value")]
)
def supplier_feedback_grid(iSupplier):
    cols=['product_block','TPNB','description','volume','Supplier_Quantile_Rank']
    df2=df[(df['supplier_name']==iSupplier)&(df['cost_component']=='Delivered Cost')].drop_duplicates()
    df2=df2[cols]
    df3=df2.groupby(['product_block','TPNB','description','volume'])['Supplier_Quantile_Rank'].sum().reset_index()
    df3['Position']=np.where(df3['Supplier_Quantile_Rank']==0,'NOT BID',
                            np.where((df3['Supplier_Quantile_Rank']>0) & (df3['Supplier_Quantile_Rank']<=2),'COMPETITIVE','NON COMPETITIVE'))
    df4=df3.sort_values(by=['product_block','TPNB'],ascending=False)
    df4.columns=['Product Block', 'TPNB', 'Description', 'Volume','Supplier Quantile Rank', 'Position']
    
    return df4.round(2).to_dict('records')




app.run_server()

Please enter your Reset
Salmon
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [25/Feb/2021 18:10:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Feb/2021 18:10:32] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [25/Feb/2021 18:10:32] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [25/Feb/2021 18:10:32] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [25/Feb/2021 18:10:32] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [25/Feb/2021 18:10:32] "POST /_dash-update-component HTTP/1.1" 200 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-4-06250752c668>", line 778, in TPNB_List
    (df['product_block'].isin(iBlock)) & (df['Is_TPNB'] == 1)][
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [NoneType]
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-4-06250752c668>", line 778, in TPNB_List
    (df['product_block'].isin(iBlock)) & (df['Is_TPNB'] == 1)][
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [NoneType]
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-4-06250752c668>", line 778, in TPNB_List
    (df['product_block'].isin(iBlock)) & (df['Is_TPNB'] == 1)][
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [NoneType]
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-4-06250752c668>", line 778, in TPNB_List
    (df['product_block'].isin(iBlock)) & (df['Is_TPNB'] == 1)][
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [NoneType]

127.0.0.1 - - [25/Feb/2021 18:10:32] "POST /_dash-update-component HTTP/1.1" 500 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-4-06250752c668>", line 790, in Quoted_Price_Comparison
    pivot_Quoted_Price_Comparison = df[(df['supplier_name'] == iSupplier) & (df['product_block'].isin(iBlock)) & ~(df['cost_component'] == 'Delivered Cost') &(df['TPNB'].isin(iTPNB))].groupby('cost_component').mean()[['quoted_cost', 'best_bid']]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [NoneType]
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-4-06250752c668>", line 790, in Quoted_Price_Comparison
    pivot_Quoted_Price_Comparison = df[(df['supplier_name'] == iSupplier) & (df['product_block'].isin(iBlock)) & ~(df['cost_component'] == 'Delivered Cost') &(df['TPNB'].isin(iTPNB))].groupby('cost_component').mean()[['quoted_cost', 'best_bid']]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [NoneType]
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-4-06250752c668>", line 790, in Quoted_Price_Comparison
    pivot_Quoted_Price_Comparison = df[(df['supplier_name'] == iSupplier) & (df['product_block'].isin(iBlock)) & ~(df['cost_component'] == 'Delivered Cost') &(df['TPNB'].isin(iTPNB))].groupby('cost_component').mean()[['quoted_cost', 'best_bid']]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [NoneType]
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-4-06250752c668>", line 790, in Quoted_Price_Comparison
    pivot_Quoted_Price_Comparison = df[(df['supplier_name'] == iSupplier) & (df['product_block'].isin(iBlock)) & ~(df['cost_component'] == 'Delivered Cost') &(df['TPNB'].isin(iTPNB))].groupby('cost_component').mean()[['quoted_cost', 'best_bid']]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [NoneType]

127.0.0.1 - - [25/Feb/2021 18:10:32] "POST /_dash-update-component HTTP/1.1" 500 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-4-06250752c668>", line 828, in Total_Price_Comparison
    pivot_Total_Price_Comparison = df[(df['supplier_name'] == iSupplier) &(df['product_block'].isin(iBlock)) & ~(df['cost_component'] == 'Delivered Cost') &(df['TPNB'].isin(iTPNB))].groupby('cost_component').mean()[['total_cost', 'best_total_cost']]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [NoneType]

127.0.0.1 - - [25/Feb/2021 18:10:32] "POST /_dash-update-component HTTP/1.1" 200 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-4-06250752c668>", line 828, in Total_Price_Comparison
    pivot_Total_Price_Comparison = df[(df['supplier_name'] == iSupplier) &(df['product_block'].isin(iBlock)) & ~(df['cost_component'] == 'Delivered Cost') &(df['TPNB'].isin(iTPNB))].groupby('cost_component').mean()[['total_cost', 'best_total_cost']]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [NoneType]
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-4-06250752c668>", line 828, in Total_Price_Comparison
    pivot_Total_Price_Comparison = df[(df['supplier_name'] == iSupplier) &(df['product_block'].isin(iBlock)) & ~(df['cost_component'] == 'Delivered Cost') &(df['TPNB'].isin(iTPNB))].groupby('cost_component').mean()[['total_cost', 'best_total_cost']]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [NoneType]
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-4-06250752c668>", line 828, in Total_Price_Comparison
    pivot_Total_Price_Comparison = df[(df['supplier_name'] == iSupplier) &(df['product_block'].isin(iBlock)) & ~(df['cost_component'] == 'Delivered Cost') &(df['TPNB'].isin(iTPNB))].groupby('cost_component').mean()[['total_cost', 'best_total_cost']]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [NoneType]

127.0.0.1 - - [25/Feb/2021 18:10:33] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [25/Feb/2021 18:10:33] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [25/Feb/2021 18:10:33] "POST /_dash-update-component HTTP/1.1" 200 -
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:493: FutureWarning:

Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

127.0.0.1 - - [25/Feb/2021 18:10:33] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [25/Feb/2021 18:10:33] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [25/Feb/2021 18:10:33] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [25/Feb/2021 18:10:33] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [25/Feb/2021 18:10:33] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [25/Feb/2021 18:10:33] "POST /_dash-update-component HTTP/1.1" 200 -

In [92]:
block_grid_cols=['product_block',
 'TPNB',
 'volume',
 'negotiation_index',
 'current_cost',
 'No_Bids',
 'best_supplier',
 'vol_avg',
 'NI_Avg',
 'Action_Priority',
 'lowest_bidder_cost',
 'Risk',
 'max_bid_supplier',
 'Acetaia Bellei',
 'Baxters 1',
 'Granarolo UK',
 'Gruppo Olitalia',
 'Kiril-Mischeff',
 'LDH Ltd',
 'Mikado UK',
 'RHAMAR',
 'Viva Foods Ltd']
suppliers_list,block_grid_cols
block_grid_cols2=['product_block',
 'TPNB',
 'volume',
 'negotiation_index',
 'current_cost',
 'No_Bids',
 'best_supplier',
 'vol_avg',
 'NI_Avg',
 'Action_Priority',
 'lowest_bidder_cost',
 'Risk',
 'max_bid_supplier']
block_grid_cols2.extend(suppliers_list)
block_grid_cols2

['product_block',
 'TPNB',
 'volume',
 'negotiation_index',
 'current_cost',
 'No_Bids',
 'best_supplier',
 'vol_avg',
 'NI_Avg',
 'Action_Priority',
 'lowest_bidder_cost',
 'Risk',
 'max_bid_supplier',
 'DAWNFRESH SEAFOODS LTD (VF',
 'MOWI SCOTLAND',
 'SEACHILL UK LTD (VF']

In [71]:
df_sup=df[(df['product_block']=='Tesco Fresh Fish')&(df['cost_component']=='Delivered Cost')]
pivot = df_sup[['supplier_name','product_block','Is_TPNB','TPNB']].pivot_table(index=['supplier_name','product_block'],columns=['Is_TPNB'],aggfunc='count')
pivot.columns = pivot.columns.droplevel(0)
pivot_2 = pivot.reset_index().rename_axis(None, axis=1)
pivot_2
cols = [0, 1]
# pivot_2[cols] = pivot_2[cols].div(pivot_2[cols].sum(axis=1), axis=0).multiply(100)
# pivot_2.fillna(0)
# fig = px.bar(pivot_2, x='supplier_name', y=1,title="Supplier Coverage %",
#              color="product_block",
#              barmode="group",
#              labels={
#                      "1": "%",
#                      "supplier_name": "Supplier Name",
#                      "product_block":"Product Block"
#                  })



# fig.show()

                supplier_name     product_block   1
0  DAWNFRESH SEAFOODS LTD (VF  Tesco Fresh Fish  11
1               MOWI SCOTLAND  Tesco Fresh Fish  11
2         SEACHILL UK LTD (VF  Tesco Fresh Fish  11

In [5]:
upper_quartile

       product_block  Supplier_Quantile_Rank
0  Specialty Vinegar                       5

In [6]:
lower_Quartile

       product_block  Supplier_Quantile_Rank
0       Malt Vinegar                       7
1  Specialty Vinegar                       1

In [41]:
pbs=df['product_block'].drop_duplicates().to_frame()
pbs=pbs.rename(columns={'product_block':'Product Block'})
product_block_position=pbs.merge(product_block_position,on=['Product Block'],how='left')
product_block_position['Bid %']=product_block_position['Bid %'].fillna(0)
product_block_position['Competitive']=product_block_position['Competitive'].fillna('Non Competitive')
product_block_position['Reason']=product_block_position['Reason'].fillna('You bid on less than 60% of the block and less than 40% of them were competitive')
product_block_position

,Product Block,Bid %,Competitive,Reason
0,Balsamic Vinegar,0.0,Non Competitive,You bid on less than 60% of the block and less...
1,Malt Vinegar,100.0,Non Competitive,You bid on more than 80% of the block but less...
2,Specialty Vinegar,100.0,Competitive,You bid on more than 80% of the block and more...

In [178]:
block_grid=df[(df['cost_component']=='Delivered Cost')].groupby(['TPNB','supplier_name']).agg({'Is_TPNB':'mean'}).reset_index()
block_grid=block_grid.sort_values(by=['Is_TPNB'],ascending=False)
block_grid['Is_TPNB']=block_grid['Is_TPNB']*100
block_grid = block_grid.pivot_table(index=['TPNB'],columns=['supplier_name'])
block_grid.columns = block_grid.columns.droplevel(0)
block_grid = block_grid.reset_index().rename_axis(None, axis=1)
block_grid

,TPNB,Acetaia Bellei,Baxters 1,Granarolo UK,Gruppo Olitalia,Kiril-Mischeff,LDH Ltd,Mikado UK,RHAMAR,Viva Foods Ltd
0,1,0,100,0,0,0,0,100,0,0
1,2,0,100,0,0,0,0,100,0,0
2,50047462,0,100,0,0,0,0,100,0,0
3,50047479,0,100,0,0,0,0,100,0,0
4,50342734,0,100,0,0,0,100,100,100,0
5,50342740,0,100,0,0,0,100,100,100,0
6,51115622,100,0,100,100,100,100,0,100,100
7,60546645,0,100,0,0,0,0,100,0,0
8,60564813,100,0,100,100,100,100,0,100,100
9,63840608,100,0,100,100,100,100,0,100,100
10,83344526,0,100,0,0,0,100,100,100,0
11,83344532,0,0,0,0,0,100,100,100,0
12,85204217,100,0,100,100,100,100,0,100,100
13,85244682,0,100,0,0,0,0,100,0,0
14,85256092,0,0,100,100,100,100,0,100,100
15,85291999,0,100,0,0,0,100,100,100,0
16,85292007,0,100,0,0,0,100,100,100,0
17,85292013,0,100,0,0,0,0,100,0,0

In [177]:
block_grid=df[(df['cost_component']=='Delivered Cost')].groupby(['TPNB','supplier_name']).agg({'Is_TPNB':'mean'}).reset_index()
block_grid=block_grid.sort_values(by=['Is_TPNB'],ascending=False)

block_grid

         TPNB    supplier_name  Is_TPNB
81   63840608   Acetaia Bellei      100
128  85256092     Granarolo UK      100
76   60564813   Kiril-Mischeff      100
75   60564813  Gruppo Olitalia      100
74   60564813     Granarolo UK      100
..        ...              ...      ...
47   50342740     Granarolo UK        0
45   50342740   Acetaia Bellei        0
44   50342734   Viva Foods Ltd        0
40   50342734   Kiril-Mischeff        0
161  85292013   Viva Foods Ltd        0

[162 rows x 3 columns]

In [182]:
cols=list(df2.columns)
cols

['index',
 'product_block',
 'TPNB',
 'volume',
 'negotiation_index',
 'current_cost',
 'No_Bids',
 'best_supplier',
 'vol_avg',
 'NI_Avg',
 'Action_Priority',
 'lowest_bidder_cost',
 'Risk',
 'max_bid_supplier',
 'Acetaia Bellei',
 'Baxters 1',
 'Granarolo UK',
 'Gruppo Olitalia',
 'Kiril-Mischeff',
 'LDH Ltd',
 'Mikado UK',
 'RHAMAR',
 'Viva Foods Ltd']

In [4]:
df.head(2)

,Phase,supplier_name,product_block,TPNB,description,Is_TPNB,Is_NPD,Savings,cost_component,quoted_cost,...,current_cost,current_cost_wgt,negotiation_index,negotiation_value,No_Bids,Impact,TPN_component,Supplier_Quantile,Supplier_Quantile_Rank,buyer
0,Phase1,Baxters 1,Balsamic Vinegar,51115622,TESCO BALSAMIC VINEGAROF MODENA 250ML,0,0.0,-636572.72,Delivered Cost,0.0,...,0.49,0.304512,0.408528,530730.423659,7,-597598.88,51115622-Delivered Cost,0.125,1.0,Cooking Ingredients
1,Phase1,Baxters 1,Balsamic Vinegar,51115622,TESCO BALSAMIC VINEGAROF MODENA 250ML,0,0.0,-636572.72,A:Raw Materials Cost,NaN,...,0.49,0.304512,0.408528,530730.423659,7,0.00,51115622-A:Raw Materials Cost,NaN,NaN,Cooking Ingredients

In [5]:
df.columns

Index(['Phase', 'supplier_name', 'product_block', 'TPNB', 'description',
       'Is_TPNB', 'Is_NPD', 'Savings', 'cost_component', 'quoted_cost',
       'best_bid', 'best_supplier', 'volume', 'impact', 'quoted_cost_wgt',
       'best_bid_wgt', 'total_cost', 'best_total_cost', 'total_cost_wgt',
       'best_total_cost_wgt', 'current_cost', 'current_cost_wgt',
       'negotiation_index', 'negotiation_value', 'No_Bids', 'Impact',
       'TPN_component', 'Supplier_Quantile', 'Supplier_Quantile_Rank',
       'buyer'],
      dtype='object')

In [52]:
cols=['product_block','TPNB','description','volume','Supplier_Quantile_Rank']
df2=df[(df['supplier_name']==iSupplier)&(df['cost_component']=='Delivered Cost')].drop_duplicates()
df2=df2[cols]
df3=df2.groupby(['product_block','TPNB','description','volume'])['Supplier_Quantile_Rank'].sum().reset_index()
df3['Position']=np.where(df3['Supplier_Quantile_Rank']==0,'NOT BID',
                        np.where((df3['Supplier_Quantile_Rank']>0) & (df3['Supplier_Quantile_Rank']<=2),'COMPETITIVE','NON COMPETITIVE'))
df4=df3.sort_values(by=['product_block','TPNB'],ascending=False)
df4

,product_block,TPNB,description,volume,Supplier_Quantile_Rank,Position
17,Specialty Vinegar,85292007,JACK'S RED WINE VINEGAR350ML,1716,3.0,NON COMPETITIVE
16,Specialty Vinegar,85291999,JACK'S WHITE WINE VINEGAR 350ML,3071,3.0,NON COMPETITIVE
15,Specialty Vinegar,83344532,TESCO SHERRY VINEGAR 350ML,50000,4.0,NON COMPETITIVE
14,Specialty Vinegar,83344526,TESCO CIDER VINEGAR 350ML,678610,3.0,NON COMPETITIVE
13,Specialty Vinegar,50342740,TESCO WHITE WINE VINEGAR 350ML,1480234,3.0,NON COMPETITIVE
12,Specialty Vinegar,50342734,TESCO RED WINE VINEGAR 350ML,776855,3.0,NON COMPETITIVE
11,Malt Vinegar,85292013,JACK'S DISTILLEDVINEGAR 568ML,8631,0.0,NOT BID
10,Malt Vinegar,85244682,JACK'S MALT VINEGAR 568ML,12364,0.0,NOT BID
9,Malt Vinegar,60546645,TESCO DISTILLED VINEGAR 568ML,3595389,0.0,NOT BID
8,Malt Vinegar,50047479,TESCO MALT VINEGAR 1.14L,336560,0.0,NOT BID
7,Malt Vinegar,50047462,TESCO MALT VINEGAR 568ML,1900373,0.0,NOT BID
6,Malt Vinegar,2,HS Malt Vinegar PM45 284ml,166428,0.0,NOT BID
5,Malt Vinegar,1,HS Distilled Malt Vinegar PM45 284ml,108672,0.0,NOT BID
4,Balsamic Vinegar,85256092,JACK'S BALSAMIC VINEGAR OF MODENA 250ML,3444,4.0,NON COMPETITIVE
3,Balsamic Vinegar,85204217,TESCO DRIZZLE WITH BALSAMIC VINEGAR 215ML,565836,2.0,COMPETITIVE
2,Balsamic Vinegar,63840608,TESCO FINEST BALS VINEGAR OF MODENA 250ML,78310,2.0,COMPETITIVE
1,Balsamic Vinegar,60564813,TESCO ORGANIC BALSAMIC VINEGAROF MODENA 250ML,143747,2.0,COMPETITIVE
0,Balsamic Vinegar,51115622,TESCO BALSAMIC VINEGAROF MODENA 250ML,1299128,4.0,NON COMPETITIVE

In [53]:
df4.columns

Index(['product_block', 'TPNB', 'description', 'volume',
       'Supplier_Quantile_Rank', 'Position'],
      dtype='object')

In [153]:
cols=['supplier_name','product_block','TPNB','volume','negotiation_index','current_cost','No_Bids','best_supplier','Supplier_Quantile_Rank']
df3=df[cols][(df['supplier_name']=='LDH Ltd')&(df['cost_component']=='Delivered Cost')&(df['Is_TPNB']==1)].drop_duplicates()
product_block_count=df3.product_block.nunique()

df4=df3.groupby(['supplier_name'])['product_block','TPNB'].nunique().reset_index()

df['TPNB'].nunique()

df4['Total_Product_Bid%']=round((df4['TPNB']/df['TPNB'].nunique())*100,0)

upper_quartile=df3[(df3['Supplier_Quantile_Rank'].isin([1,2]))&(df3['supplier_name']=='LDH Ltd')]
upper_quartile=upper_quartile.groupby(['product_block'])['Supplier_Quantile_Rank'].count().reset_index()
upper_quartile

lower_Quartile=df3[(df3['Supplier_Quantile_Rank'].isin([3,4]))&(df3['supplier_name']=='LDH Ltd')]
lower_Quartile=lower_Quartile.groupby(['product_block'])['Supplier_Quantile_Rank'].count().reset_index()
lower_Quartile



upper_quartile_tpnb=sum(upper_quartile['Supplier_Quantile_Rank'])

lower_quartile_tpnb=sum(lower_Quartile['Supplier_Quantile_Rank'])

top_2_quartile_per=(upper_quartile_tpnb/(upper_quartile_tpnb+lower_quartile_tpnb))*100

df4['Overall_position']=np.where(((df4['Total_Product_Bid%']>60)&(top_2_quartile_per>25)),'Competitive',
                                 np.where(((df4['Total_Product_Bid%']>40)&(top_2_quartile_per>40)),'Competitive_2','Non Competitive'))
df4

df4['Reason']=np.where(((df4['Total_Product_Bid%']>60) & (top_2_quartile_per>25)),'You bid on more than 60% of the block and more than 25% of your bids were competitive',
                                 np.where(((df4['Total_Product_Bid%']>40) & (top_2_quartile_per>40)),'You have not bid on a high % of products but more than 40% of your bids are competitive',
                                        np.where((df4['Total_Product_Bid%']<40),'You have bid on a very low number of products','A high percentage of your bids are not in the competitive zone')))
df4
cols=['supplier_name', 'product_block', 'TPNB', 'Total_Product_Bid%',
       'Overall_position']
df5=df4[cols]

quartile=upper_quartile.merge(lower_Quartile,on=['product_block'],how='outer')

quartile['upper_bid%']=((quartile['Supplier_Quantile_Rank_x'])/(quartile['Supplier_Quantile_Rank_x']+quartile['Supplier_Quantile_Rank_y']))*100

tpnb_bid=df2.groupby(['product_block'])['TPNB'].nunique().reset_index()
tpnb_bid

total_tpnb=df.groupby(['product_block'])['TPNB'].nunique().reset_index()
total_tpnb

bid_per=tpnb_bid.merge(total_tpnb,how='inner',on=['product_block'])

bid_per['Bid_%']=(bid_per['TPNB_x']/bid_per['TPNB_y'])*100
bid_per

product_block_position=quartile.merge(bid_per[['product_block','Bid_%']],on=['product_block'],how='outer')
product_block_position

product_block_position['competitive']=np.where(((product_block_position['Bid_%']>=80) & (product_block_position['upper_bid%']>=25)),'Competitive',
                                         np.where(((product_block_position['Bid_%']>=60) & (product_block_position['upper_bid%']>=40)),'Competitive_2','Non Competitive'))



product_block_position['reason']=np.where(product_block_position['competitive']=='Competitive','You bid on more than 80% of the block and more than 25% of your bids were competitive',
                                 np.where(product_block_position['competitive']=='Competitive_2','You bid on less than 60% of the block and less than 40% of them were competitive','You bid on more than 80% of the block but less than 25% of your bids were competitive'))

cols=['product_block','Bid_%','competitive','reason']
product_block_position=product_block_position[cols]
product_block_position

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning:

Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

,product_block,Bid_%,competitive,reason
0,Balsamic Vinegar,100.0,Competitive,You bid on more than 80% of the block and more...
1,Specialty Vinegar,100.0,Non Competitive,You bid on more than 80% of the block but less...
2,Malt Vinegar,100.0,Non Competitive,You bid on more than 80% of the block but less...

In [86]:
df4.columns

Index(['supplier_name', 'product_block', 'TPNB', 'Total_Product_Bid%',
       'Overall_position', 'Reason'],
      dtype='object')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning:

Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

([{'supplier_name': 'LDH Ltd',
   'product_block': 2,
   'TPNB': 11,
   'Total_Product_Bid%': 61.0,
   'Overall_position': 'Competitive'}],
 'You bid on more than 60% of the block and more than 25% of your bids were competitive')