In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel(r'C:\Users\IN22912959\OneDrive - Tesco\Documents\Supplier Score Card\Analysis\TFMS analysis Template 12 08 2020.xlsx',sheet_name='TQC Data')

In [3]:
cols=['Supplier_Code','Supplier_Name','Site_Code','Site_Name','Comm_Supplier_Name','Supplier_Number']
df.columns

Index(['Unnamed: 0', 'lookup', 'Origin', 'Supplier_Code', 'Supplier_Name',
       'Site_Code', 'Site_Name', 'Audit', 'Last_Audit_Date',
       'Last_Audit_Score', 'Score', 'Due_Date', 'From_Date', 'To_Date',
       'Audit_Visit_Id', 'Audit_Visit_Status', 'Site_Status',
       'Lead_Technical_Manager', 'Business_Units', 'Country', 'Path',
       'OBL_Count', 'BL_Count', 'Junior_Buyer', 'Buyer', 'Buying_Controller',
       'Category_Director', 'Commercial_Director', 'Supplier_Number',
       'Comm_Supplier_Name', 'Category_Director_Corrected',
       'Commercial_Director_Corrected', 'Buying_Controller_Corrected',
       'Junior_Buyer_Corrected', 'Match?', 'Empty Column 1', 'Empty Column 2',
       'Empty Column 3', 'Empty Column 4', 'Empty Column 5', 'Empty Column 6',
       'Empty Column 7', 'Empty Column 8', 'Empty Column 9',
       'Empty Column 10'],
      dtype='object')

In [4]:
df2=df[cols]
df2.head()

,Supplier_Code,Supplier_Name,Site_Code,Site_Name,Comm_Supplier_Name,Supplier_Number
0,11937,Bakkavor,112,Bakkavör Salads Spalding - Delicatessen,BAKKAVOR SPALDING(FF(VF,45494.0
1,11937,Bakkavor,112,Bakkavör Salads Spalding - Delicatessen,BAKKAVOR FOODS LTD TA(VF,60054.0
2,11937,Bakkavor,112,Bakkavör Salads Spalding - Delicatessen,BAKKAVOR FOODS LTD TA(VF,35102.0
3,11937,Bakkavor,112,Bakkavör Salads Spalding - Delicatessen,BAKKAVOR FOODS LTD TA(VF,50610.0
4,11937,Bakkavor,112,Bakkavör Salads Spalding - Delicatessen,BAKKAVOR SPALDING(FF(VF,45494.0

In [5]:
df3=df2[['Site_Name','Site_Code','Comm_Supplier_Name']]

In [6]:
df3.drop_duplicates().head()

,Site_Name,Site_Code,Comm_Supplier_Name
0,Bakkavör Salads Spalding - Delicatessen,112,BAKKAVOR SPALDING(FF(VF
1,Bakkavör Salads Spalding - Delicatessen,112,BAKKAVOR FOODS LTD TA(VF
101,Bakkavör Salads Spalding - Delicatessen,112,BAKKAVOR FOODS LTD TA(FF(VF
130,Bakkavör Salads Spalding - Delicatessen,112,BAKKAVOR SPALDING(MP(VF
131,Bakkavör Salads Spalding - Delicatessen,112,BAKKAVOR SPALDING(VF

In [7]:
df3.melt(id_vars=['Comm_Supplier_Name'])

,Comm_Supplier_Name,variable,value
0,BAKKAVOR SPALDING(FF(VF,Site_Name,Bakkavör Salads Spalding - Delicatessen
1,BAKKAVOR FOODS LTD TA(VF,Site_Name,Bakkavör Salads Spalding - Delicatessen
2,BAKKAVOR FOODS LTD TA(VF,Site_Name,Bakkavör Salads Spalding - Delicatessen
3,BAKKAVOR FOODS LTD TA(VF,Site_Name,Bakkavör Salads Spalding - Delicatessen
4,BAKKAVOR SPALDING(FF(VF,Site_Name,Bakkavör Salads Spalding - Delicatessen
...,...,...,...
49437,OBRIEN FINE FOODS,Site_Code,I0044
49438,OBRIEN FINE FOODS,Site_Code,I0044
49439,KEELINGS RETAIL UN CO(FF(VF,Site_Code,KL3
49440,KEELINGS RETAIL UN CO(FF(VF,Site_Code,KL3
49441,KEELINGS RETAIL UN CO(FF(VF,Site_Code,KL3

In [8]:
site_Codes=[]
dictt={}
for i in df3['Comm_Supplier_Name'].drop_duplicates():
    df4=df3[['Site_Code','Site_Name']][df3['Comm_Supplier_Name']==i].drop_duplicates()
    dictt[i]=df4.reset_index(drop=True)

In [9]:
df6=pd.DataFrame()
for i in df3['Comm_Supplier_Name'].drop_duplicates():
#     if(i=='BAKKAVOR SPALDING(FF(VF' or i=='OBRIEN FINE FOODS' or i=='KEELINGS RETAIL UN CO(FF(VF'):

    df4=df3[['Comm_Supplier_Name','Site_Code','Site_Name']][df3['Comm_Supplier_Name']==i].drop_duplicates()
    df4['col']=df4['Site_Code'].map(str) + '-' + df['Site_Name'].map(str)
    df4=df4.drop(['Site_Code','Site_Name'],axis=1)
    df5=df4.drop_duplicates().pivot(index='Comm_Supplier_Name', columns='col', values='col')
    df6=pd.concat([df6,df5])
#     display(df6)

In [10]:
display(df6)

,NaN,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,0244DC-Fountain Frozen Ltd,0247H-Samworth Bros (Walkers Midshire-Cooked Meat),0247S-Samworth Bros (Walkers Midshire - Sausage),0354FK-GREENYARD FROZEN uk LTD,0411A-Youngs Seafood Limited (Humberstone Road E factory),0715D-Heygates Ltd,...,JU01-GFS UK Produce Jupiter Marketing Newport,"MT05-JDM Food Group Ltd, GFS UK Produce Maritime Sales Ltd",0712T-ADM Milling Tilbury,212751-ADM Milling Corby,212936-ADM Milling Edinburgh,211639-JDS Foods,213895-Standard Brands,4313-Punjana Ltd,4425-Irish Yogurts,I0044-O Brien Fine Foods
Comm_Supplier_Name,,,,,,,,,,,,,,,,,,,,,
BAKKAVOR SPALDING(FF(VF,NaN,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BAKKAVOR FOODS LTD TA(VF,NaN,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BAKKAVOR FOODS LTD TA(FF(VF,NaN,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BAKKAVOR SPALDING(MP(VF,NaN,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BAKKAVOR SPALDING(VF,NaN,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
JDS FOODS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,211639-JDS Foods,NaN,NaN,NaN,NaN
TENNANT & RUTTLE DIST(EURO(ROI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,213895-Standard Brands,NaN,NaN,NaN
PUNJANA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4313-Punjana Ltd,NaN,NaN
IRISH YOGURTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4425-Irish Yogurts,NaN
OBRIEN FINE FOODS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I0044-O Brien Fine Foods

In [11]:
df7 = df6.T.apply(lambda x: pd.Series(x.dropna().values)).fillna('')
display(df7.T)

,0,1,2,3,4,5,6,7,8,9,...,46,47,48,49,50,51,52,53,54,55
Comm_Supplier_Name,,,,,,,,,,,,,,,,,,,,,
BAKKAVOR SPALDING(FF(VF,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,102114-Katsouris - Cumberland Avenue,103140-Bakkavor Pizza (Holbeach),112-Bakkavör Salads Spalding - Delicatessen,210207-Bakkavor Bread (Crewe),212123-Katsouris - Abbeydale Fry,35102-001-Bakkavor - Wigan,3663-Bakkavor Bread (Nantwich),...,,,,,,,,,,
BAKKAVOR FOODS LTD TA(VF,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,102114-Katsouris - Cumberland Avenue,103140-Bakkavor Pizza (Holbeach),112-Bakkavör Salads Spalding - Delicatessen,210207-Bakkavor Bread (Crewe),212123-Katsouris - Abbeydale Fry,35102-001-Bakkavor - Wigan,3663-Bakkavor Bread (Nantwich),...,,,,,,,,,,
BAKKAVOR FOODS LTD TA(FF(VF,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,102114-Katsouris - Cumberland Avenue,103140-Bakkavor Pizza (Holbeach),112-Bakkavör Salads Spalding - Delicatessen,210207-Bakkavor Bread (Crewe),212123-Katsouris - Abbeydale Fry,35102-001-Bakkavor - Wigan,3663-Bakkavor Bread (Nantwich),...,,,,,,,,,,
BAKKAVOR SPALDING(MP(VF,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,112-Bakkavör Salads Spalding - Delicatessen,,,,,,,,...,,,,,,,,,,
BAKKAVOR SPALDING(VF,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,102114-Katsouris - Cumberland Avenue,103140-Bakkavor Pizza (Holbeach),112-Bakkavör Salads Spalding - Delicatessen,210207-Bakkavor Bread (Crewe),212123-Katsouris - Abbeydale Fry,35102-001-Bakkavor - Wigan,3663-Bakkavor Bread (Nantwich),...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
JDS FOODS,211639-JDS Foods,,,,,,,,,,...,,,,,,,,,,
TENNANT & RUTTLE DIST(EURO(ROI,213895-Standard Brands,,,,,,,,,,...,,,,,,,,,,
PUNJANA,4313-Punjana Ltd,,,,,,,,,,...,,,,,,,,,,
IRISH YOGURTS,4425-Irish Yogurts,,,,,,,,,,...,,,,,,,,,,
OBRIEN FINE FOODS,I0044-O Brien Fine Foods,,,,,,,,,,...,,,,,,,,,,

In [12]:
# df7.T.to_excel('Nisar.xlsx')

In [13]:
Site_Details=df7.T

In [14]:
Site_Details.head()

,0,1,2,3,4,5,6,7,8,9,...,46,47,48,49,50,51,52,53,54,55
Comm_Supplier_Name,,,,,,,,,,,,,,,,,,,,,
BAKKAVOR SPALDING(FF(VF,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,102114-Katsouris - Cumberland Avenue,103140-Bakkavor Pizza (Holbeach),112-Bakkavör Salads Spalding - Delicatessen,210207-Bakkavor Bread (Crewe),212123-Katsouris - Abbeydale Fry,35102-001-Bakkavor - Wigan,3663-Bakkavor Bread (Nantwich),...,,,,,,,,,,
BAKKAVOR FOODS LTD TA(VF,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,102114-Katsouris - Cumberland Avenue,103140-Bakkavor Pizza (Holbeach),112-Bakkavör Salads Spalding - Delicatessen,210207-Bakkavor Bread (Crewe),212123-Katsouris - Abbeydale Fry,35102-001-Bakkavor - Wigan,3663-Bakkavor Bread (Nantwich),...,,,,,,,,,,
BAKKAVOR FOODS LTD TA(FF(VF,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,102114-Katsouris - Cumberland Avenue,103140-Bakkavor Pizza (Holbeach),112-Bakkavör Salads Spalding - Delicatessen,210207-Bakkavor Bread (Crewe),212123-Katsouris - Abbeydale Fry,35102-001-Bakkavor - Wigan,3663-Bakkavor Bread (Nantwich),...,,,,,,,,,,
BAKKAVOR SPALDING(MP(VF,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,112-Bakkavör Salads Spalding - Delicatessen,,,,,,,,...,,,,,,,,,,
BAKKAVOR SPALDING(VF,0112A-Bakkavor Salads Spalding- Factory 1,0112C-Soups and Sauces,0112E-Bakkavör Spalding - Cerberus,102114-Katsouris - Cumberland Avenue,103140-Bakkavor Pizza (Holbeach),112-Bakkavör Salads Spalding - Delicatessen,210207-Bakkavor Bread (Crewe),212123-Katsouris - Abbeydale Fry,35102-001-Bakkavor - Wigan,3663-Bakkavor Bread (Nantwich),...,,,,,,,,,,

In [15]:
tpps=pd.read_excel(r'C:\Users\IN22912959\OneDrive - Tesco\Documents\Supplier Score Card\Analysis\suppliers (top 10 & tpp).xlsx',sheet_name='top 10 & tpp')

In [16]:
tpps.head(2)

,Category,Category_2,Parent Supplier Name,Unnamed: 3,Sales,CoGS,TPP
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bakery & Dairy,BAKERY&DAIR Y.,ROBERT WISEMAN & SONS LTD,NaN,318654540.0,-243342124,Y

In [17]:
tpps=tpps.dropna(how='all')
tpps=tpps.drop(['Unnamed: 3','Sales','CoGS'],axis=1)
tpps['TPP']=tpps['TPP'].fillna(0)
tpps['TPP']=tpps['TPP'].replace({'Y':1})
tpps.head()

         Category        Category_2       Parent Supplier Name  TPP
1  Bakery & Dairy  BAKERY&DAIR   Y.  ROBERT WISEMAN & SONS LTD    1
2  Bakery & Dairy  BAKERY&DAIR   Y.                 ARLA FOODS    1
3  Bakery & Dairy  BAKERY&DAIR   Y.                ADAMS FOODS    1
4  Bakery & Dairy  BAKERY&DAIR   Y.             WARBURTONS LTD    0
5  Bakery & Dairy  BAKERY&DAIR   Y.            DAIRY CREST LTD    0

In [18]:
tpps['Category_2'].drop_duplicates()

1     BAKERY&DAIR   Y.
12                 NaN
14    MF            P.
28    PREPARED FOOD S.
41    PRODUC        E.
64    GROCER        Y.
66    HB&WELLNES    S.
68    HOUSEHOLD&PE  T.
69    IMPULS        E.
71    BW            S.
Name: Category_2, dtype: object

In [19]:
psd=pd.read_excel(r'C:\Users\IN22912959\OneDrive - Tesco\Documents\Supplier Score Card\Analysis\Parent Supplier and Supplier Details.xlsx',sheet_name='Sheet2')

In [20]:
psd.head(2)

,Parent_Supplier,Parent_Supplier_Name,Supplier,Supplier_Name,Category_Director,Junior_Buyer,Unnamed: 6,Unnamed: 7
0,10002,MANGROVE GLOBAL LTD,67776,MANGROVE GLOBAL LTD (DUTY PAID,BW S.,LIQUEUR&SPECIAL.,NaN,NaN
1,10002,MANGROVE GLOBAL LTD,69037,MANGROVE GLOBAL LTD(DUTY DEFER,BW S.,LIQUEUR&SPECIAL.,NaN,NaN

In [21]:
cols=['Parent_Supplier','Parent_Supplier_Name','Supplier','Supplier_Name','Category_Director','Junior_Buyer']
df=psd[cols].drop_duplicates()
df.head()

,Parent_Supplier,Parent_Supplier_Name,Supplier,Supplier_Name,Category_Director,Junior_Buyer
0,10002,MANGROVE GLOBAL LTD,67776,MANGROVE GLOBAL LTD (DUTY PAID,BW S.,LIQUEUR&SPECIAL.
1,10002,MANGROVE GLOBAL LTD,69037,MANGROVE GLOBAL LTD(DUTY DEFER,BW S.,LIQUEUR&SPECIAL.
2,10002,MANGROVE GLOBAL LTD,69037,MANGROVE GLOBAL LTD(DUTY DEFER,BW S.,READYTODRIN K.
3,10002,MANGROVE GLOBAL LTD,69037,MANGROVE GLOBAL LTD(DUTY DEFER,BW S.,VODKA&GIN&RU M.
4,10015,HEALTHY BY NATURE LTD,67838,HEALTHY BY NATURE LTD,HB&WELLNES S.,NUTRICENTR E.

In [22]:
TPP=tpps
TPP.head()

         Category        Category_2       Parent Supplier Name  TPP
1  Bakery & Dairy  BAKERY&DAIR   Y.  ROBERT WISEMAN & SONS LTD    1
2  Bakery & Dairy  BAKERY&DAIR   Y.                 ARLA FOODS    1
3  Bakery & Dairy  BAKERY&DAIR   Y.                ADAMS FOODS    1
4  Bakery & Dairy  BAKERY&DAIR   Y.             WARBURTONS LTD    0
5  Bakery & Dairy  BAKERY&DAIR   Y.            DAIRY CREST LTD    0

In [23]:
df2=TPP.merge(df,left_on=['Category_2','Parent Supplier Name'],right_on=['Category_Director','Parent_Supplier_Name'],how='left')

In [24]:
df2.head(2)

,Category,Category_2,Parent Supplier Name,TPP,Parent_Supplier,Parent_Supplier_Name,Supplier,Supplier_Name,Category_Director,Junior_Buyer
0,Bakery & Dairy,BAKERY&DAIR Y.,ROBERT WISEMAN & SONS LTD,1,741.0,ROBERT WISEMAN & SONS LTD,34758.0,MULLER UK & IRELAND GROUP LLP,BAKERY&DAIR Y.,KIDS YOGHUR T.
1,Bakery & Dairy,BAKERY&DAIR Y.,ROBERT WISEMAN & SONS LTD,1,741.0,ROBERT WISEMAN & SONS LTD,47877.0,MULLER UK & IRELAND GROUP LLP,BAKERY&DAIR Y.,BUTTERSPREAD S.

In [25]:
cols=['Category','Parent_Supplier_Name','Parent_Supplier','Supplier_Name','Supplier','TPP','Junior_Buyer']
df3=df2[cols].drop_duplicates()

In [26]:
df4=df3

In [27]:
df4.set_index('Supplier_Name')

,Category,Parent_Supplier_Name,Parent_Supplier,Supplier,TPP,Junior_Buyer
Supplier_Name,,,,,,
MULLER UK & IRELAND GROUP LLP,Bakery & Dairy,ROBERT WISEMAN & SONS LTD,741.0,34758.0,1,KIDS YOGHUR T.
MULLER UK & IRELAND GROUP LLP,Bakery & Dairy,ROBERT WISEMAN & SONS LTD,741.0,47877.0,1,BUTTERSPREAD S.
MULLER UK & IRELAND GROUP LLP,Bakery & Dairy,ROBERT WISEMAN & SONS LTD,741.0,34758.0,1,ADULTYOGURT S.
MULLER UK & IRELAND GROUP LLP,Bakery & Dairy,ROBERT WISEMAN & SONS LTD,741.0,34758.0,1,DAIRYALTERNATIV.
MULLER UK & IRELAND GROUP LLP,Bakery & Dairy,ROBERT WISEMAN & SONS LTD,741.0,44422.0,1,CREA M.
...,...,...,...,...,...,...
BURTS POTATO CHIPS LIMITED,Impulse,BURTS POTATO CHIPS LTD,6707.0,63099.0,0,MULTICRISP S.
BURTS POTATO CHIPS LIMITED,Impulse,BURTS POTATO CHIPS LTD,6707.0,63099.0,0,SEASONBIGBAGC S.
BURTS POTATO CHIPS LIMITED,Impulse,BURTS POTATO CHIPS LTD,6707.0,63099.0,0,BIGBAGC S.
BURTS POTATO CHIPS LIMITED,Impulse,BURTS POTATO CHIPS LTD,6707.0,63099.0,0,NUTSSINGLCRISPS.
INDEVIN SUPPLY LIMITED(FOB,BWS,INDEVIN SUPPLY LIMITED,10791.0,68963.0,0,NEWZEALAND O.

In [28]:
final=df4.merge(Site_Details,right_on=['Comm_Supplier_Name'],left_on=['Supplier_Name'],how='left')

In [29]:
final.to_excel('Nisar_2.xlsx')